APP_NAME = 'iyfconnect'
REFRESH_TOKEN = 'refresh_token'
ACCESS_TOKEN = 'access_token'
EMAIL = 'email'
PASSWORD = 'password'
VERIFICATION_CODE = 'verification_code'
NEW_PASSWORD = 'new_password'
OLD_PASSWORD = 'old_password'